In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\loq\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\loq\anaconda3\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\loq\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\loq\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\loq\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
info = {
    "Name": ["Rahul","Ankita","Jibitesh"],
    "CGPA": [9.5,10,9.9]
}
df = pd.DataFrame(info)
df

       Name  CGPA
0     Rahul   9.5
1    Ankita  10.0
2  Jibitesh   9.9

In [7]:
df = pd.DataFrame(info, ["A","B","C"])
df

       Name  CGPA
A     Rahul   9.5
B    Ankita  10.0
C  Jibitesh   9.9